name: Master - Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Setup .NET Framework 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.4.21255.9'
        include-prerelease: true

    - name: Install dependencies for Source
      run: dotnet restore "Source\TeamSwim.Extensions\TeamSwim.Extensions.csproj"
    
    - name: Install dependencies for Tests
      run: dotnet restore "Source\TeamSwim.Extensions.Tests\TeamSwim.Extensions.Tests.csproj"

    - name: Build
      run: dotnet build "Source\TeamSwim.Extensions\TeamSwim.Extensions.csproj" --configuration Release --no-restore

    # - name: Test
    #   run: dotnet test "Source\TeamSwim.Extensions.Tests\TeamSwim.Extensions.Tests.csproj" --no-restore --verbosity normal

    # https://github.com/codecov/codecov-action
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

    - name: Publish TeamSwim.Extensions
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Source/TeamSwim.Extensions/TeamSwim.Extensions.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
