name: Master - Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Setup .NET Framework 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.4.21255.9'
        include-prerelease: true

    - name: Install dependencies for Source
      run: dotnet restore "Source\TeamSwim.Extensions\TeamSwim.Extensions.csproj"
    
    - name: Install dependencies for Tests
      run: dotnet restore "Source\TeamSwim.Extensions.Tests\TeamSwim.Extensions.Tests.csproj"

    - name: Build
      run: dotnet build "Source\TeamSwim.Extensions\TeamSwim.Extensions.csproj" --configuration Release --no-restore

    # - name: Test
    #   run: dotnet test "Source\TeamSwim.Extensions.Tests\TeamSwim.Extensions.Tests.csproj" --no-restore --verbosity normal

    # same as publish.yml, without the NuGet publish
